# Generated by Django 6.0.2 on 2026-02-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField()),
                ('marca', models.CharField()),
                ('modelo', models.CharField()),
                ('numero_serie', models.CharField()),
                ('estado', models.CharField()),
            ],
        ),
    ]
