# Generated by Django 6.0.2 on 2026-02-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='estado',
        ),
    ]
